name: Super-Lint

on: push

jobs:
  test_schedule:
    runs-on: [self-hosted, runner-2]
    steps:
      - name: Not on Monday or Wednesday
        run: touch production
      #  run: git pull && bash runFile.sh 
